- name: Check if user is in sudoers
  raw: 'sudo -n true'
  failed_when: false
  changed_when: false
  register: sudo

- name: Remove sudo access for zuul user.
  become: yes
  file:
    path: /etc/sudoers.d/zuul
    state: absent
  when: sudo.rc == 0

- name: Prove that general sudo access is actually revoked.
  raw: '! sudo -n true'
